/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vinhlp.form;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vinhlp.role.RoleDAO;
import vinhlp.user.UserDAO;
import vinhlp.user.UserDTO;

/**
 *
 * @author Asus
 */
public class UserControllForm extends javax.swing.JFrame {

    //1. khai báo đối tượng chứa dữ liệu của table
    DefaultTableModel tblModelUser = null;

    /**
     * Creates new form UserControllForm
     */
    public UserControllForm() {
        initComponents();
        //2. khởi tạo giá trị
        tblModelUser = (DefaultTableModel) tblUser.getModel();
        loadForm();
    }

    private void loadForm() {
        UserDAO dao = new UserDAO();
        RoleDAO daoRole = new RoleDAO();
        try {
            List<UserDTO> dtos = dao.getAllUser();
            //3. reset lại bảng
            tblModelUser.setRowCount(0);
            //4.duyệt các đối tượng trong list
            for (UserDTO dto : dtos) {
                tblModelUser.addRow(dto.toVector());
            }
            daoRole.getAllRole();
            List<String> role = daoRole.getListRole();
            cbxGroup.removeAllItems();
            for (String item : role) {
                cbxGroup.addItem(item);
            }
        } catch (ClassNotFoundException e) {
            System.out.println("loadFrom: " + e.getMessage());
        } catch (SQLException e) {
            System.out.println("loadForm: " + e.getMessage());
        }
        txtPassword.setEditable(false);
        txtUsername.setEditable(false);
        btnSavepass.setVisible(false);
        lbGroup.setVisible(false);
        cbxGroup.setVisible(false);
        btnSaveGroup.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbGroup = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        cbxGroup = new javax.swing.JComboBox<>();
        btnChangePassword = new javax.swing.JButton();
        btnSavepass = new javax.swing.JButton();
        btnChangeGroup = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSaveGroup = new javax.swing.JButton();
        btnMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("List Of User"));

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Password", "Group"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Information of selected user"));

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        lbGroup.setText("Group:");

        btnChangePassword.setText("Change Password");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });

        btnSavepass.setText("Save");
        btnSavepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavepassActionPerformed(evt);
            }
        });

        btnChangeGroup.setText("Change Group");
        btnChangeGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeGroupActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete this User");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSaveGroup.setText("Save");
        btnSaveGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveGroupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lbGroup))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword)
                    .addComponent(cbxGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSavepass)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDelete)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnChangeGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSaveGroup)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGroup)
                    .addComponent(cbxGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePassword)
                    .addComponent(btnSavepass))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChangeGroup)
                            .addComponent(btnSaveGroup))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDelete))))
        );

        btnMain.setText("Back");
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMain)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        int row = 1;
        row = tblUser.getSelectedRow();
        String username = (String) tblModelUser.getValueAt(row, 0);
        txtUsername.setText(username);
        String password = (String) tblModelUser.getValueAt(row, 1);
        txtPassword.setText(password);
        String role = (String) tblModelUser.getValueAt(row, 2);
        int index = 0;
        if (role.equals("Seller")) {
            index = 1;
        } else if (role.equals("Inventory Staff")) {
            index = 2;
        }
        cbxGroup.setSelectedIndex(index);
    }//GEN-LAST:event_tblUserMouseClicked

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        txtPassword.setEditable(true);
        btnSavepass.setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnChangeGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeGroupActionPerformed
        lbGroup.setVisible(true);
        cbxGroup.setVisible(true);
        btnSaveGroup.setVisible(true);
    }//GEN-LAST:event_btnChangeGroupActionPerformed

    private void btnSavepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavepassActionPerformed
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        int role = cbxGroup.getSelectedIndex();
        if (role > 0) {
            try {
                //call dao to change password
                UserDAO dao = new UserDAO();
                boolean isUpdatePassword = dao.changePassword(username, password);
                if (isUpdatePassword) {
                    JOptionPane.showMessageDialog(this, "Update Success", "Update Process", HEIGHT);
                    loadForm();
                } else {
                    JOptionPane.showMessageDialog(this, "Update fail", "Update Process", HEIGHT);
                    loadForm();
                }
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Update Process", HEIGHT);
            }
        } else {
            JOptionPane.showMessageDialog(this, "You can't change the admin password!", "Update Process", HEIGHT);
            loadForm();
        }
    }//GEN-LAST:event_btnSavepassActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String username = txtUsername.getText();
        int role = cbxGroup.getSelectedIndex();
        if (role > 0) {
            UserDAO dao = new UserDAO();
            try {
                boolean isDelete = dao.deleteUser(username);
                if (isDelete) {
                    JOptionPane.showMessageDialog(this, "Delete Success!", "Delete User process: ", HEIGHT);
                } else {
                    JOptionPane.showMessageDialog(this, "Delete Fail!", "Delete User process: ", HEIGHT);
                }
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Delete User process: ", HEIGHT);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Can't delete the admin account!", "Delete User process: ", HEIGHT);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveGroupActionPerformed
        String username = txtUsername.getText();
        int roleNum = cbxGroup.getSelectedIndex() + 1;
        UserDAO dao = new UserDAO();
        try {
            if (roleNum == 3) {
                //check is the inventory staff is exist!
                boolean isExistInventoryStaff = dao.isExistInventoryStaff();
                if (isExistInventoryStaff) {
                    JOptionPane.showMessageDialog(this, "There is only inventory staff in the company!", "Update Role Process:", HEIGHT);
                } // end if not exist inventory staff
                else {
                    boolean isUpdateRole = dao.changeRole(username, roleNum);
                    if (isUpdateRole) {
                        JOptionPane.showMessageDialog(this, "Update Role Success!", "Update Role Process:", HEIGHT);
                        loadForm();
                    } else {
                        JOptionPane.showMessageDialog(this, "Update Role Fail!", "Update Role Process:", HEIGHT);
                    }
                }
            } else if (dao.isAdminUser(username)) {
                JOptionPane.showMessageDialog(this, "You can't change the group of admin", "Update Role Process: ", HEIGHT);
                loadForm();
            } else {
                boolean isUpdateRole = dao.changeRole(username, roleNum);
                if (isUpdateRole) {
                    JOptionPane.showMessageDialog(this, "Update Role Success!", "Update Role Process:", HEIGHT);
                    loadForm();
                } else {
                    JOptionPane.showMessageDialog(this, "Update Role Fail!", "Update Role Process:", HEIGHT);
                }
            }
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Update Role Process:", HEIGHT);
            loadForm();
        }
    }//GEN-LAST:event_btnSaveGroupActionPerformed

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        new MainFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserControllForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserControllForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserControllForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserControllForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserControllForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeGroup;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnSaveGroup;
    private javax.swing.JButton btnSavepass;
    private javax.swing.JComboBox<String> cbxGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGroup;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
